module.exports = {
  apps: [
    {
      name: "immosure-backend",
      cwd: "/var/www/immosure/backend",
      script: "/var/www/immosure/venv/bin/uvicorn",
      args: "app.main:app --host 0.0.0.0 --port 8000",
      interpreter: "none",
      instances: 2,
      exec_mode: "cluster",
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      env: {
        PYTHONPATH: "/var/www/immosure/backend",
        ENVIRONMENT: "production",
      },
      error_file: "/var/log/immosure/backend-error.log",
      out_file: "/var/log/immosure/backend-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
    },
    {
      name: "immosure-bot",
      cwd: "/var/www/immosure/backend",
      script: "/var/www/immosure/venv/bin/python",
      args: "-m app.modules.bot.run_bot",
      interpreter: "none",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "256M",
      env: {
        PYTHONPATH: "/var/www/immosure/backend",
        ENVIRONMENT: "production",
      },
      error_file: "/var/log/immosure/bot-error.log",
      out_file: "/var/log/immosure/bot-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
    },
  ],
};
